### ISSUE TITLE
Import class error

### ISSUE THREAD

**Issue by xiaozhuai** [frida/frida-compile#15]
# Case 1
In `AClass.js`
```
export default class AClass {
    // xxxxx
}
```

In `b.js`
```
import AClass from './AClass';
```

Then error occurred

```
Compilation failed: 
/Users/xiaozhuai/work/GLEavesdropper/node_modules/@babel/runtime-corejs2/helpers/esm/classCallCheck.js:1
export default function _classCallCheck(instance, Constructor) {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

# Case 2
In `fff.js`
```
export default function fff({ args }, data) {
    let [a, b] = args;
    return a;
}
```

In `c.js`
```
import AClass from './fff';
```

Then error occurred

```
Compilation failed: 
/Users/xiaozhuai/work/GLEavesdropper/node_modules/@babel/runtime-corejs2/helpers/esm/slicedToArray.js:1
import arrayWithHoles from "./arrayWithHoles";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Finally, I make this change, and it works, any ideas?
```js
        // ignore: [/[\/\\]node_modules[\/\\](@babel|core-js|core-js-pure|lodash)([\/\\]|$)/],
        ignore: [/[\/\\]node_modules[\/\\](core-js|core-js-pure|lodash)([\/\\]|$)/],
```

**Comment by Fr0stM0urne** [comment]
try
const module_name = require('module_name');

**Comment by oleavr** [comment]
This was fixed in #13.

**Comment by federicodotta** [comment]
HI @oleavr,

I still have the same error with frida-compile 10.  By looking at the code in the repository it seems that the fix code in the pull request https://github.com/frida/frida-compile/pull/13 is not present. Am I wrong?

Thank you a lot for your support

**Comment by p1s1lver** [comment]
> HI @oleavr, 你好 ，
> 
> I still have the same error with frida-compile 10. By looking at the code in the repository it seems that the fix code in the pull request #13 is not present. Am I wrong?我在 frida-compile 10 中仍然遇到同样的错误。通过查看存储库中的代码，似乎拉取请求 #13 中的修复代码不存在。我错了吗？
> 
> Thank you a lot for your support and for your great job非常感谢您的支持和出色的工作

same in 10.2.5
